//! Scan pipeline decision logic.
//!
//! Split into two stages so the "validate before hashing" ordering is
//! enforced by the types, not just convention: `build_new_video` requires an
//! already-computed `quick_hash`, so a caller cannot reach it without first
//! computing the hash themselves -- and the only reason to do that is after
//! `validate` returned `Valid`. Actual hashing/file I/O happens in
//! `src-tauri::scan`, not here.

use crate::filename_validation;

pub struct ScannedFile {
    pub file_path: String,
    pub file_name: String,
    pub file_size: u64,
    /// Filesystem mtime (Unix seconds) as of this detection. Stored on
    /// registration so a later rescan/poll can cheaply tell "unchanged"
    /// apart from "needs rehash" via `reconcile::classify_discovered_file`
    /// without recomputing quick_hash.
    pub mtime: i64,
}

pub enum ValidationOutcome {
    Valid,
    Invalid { detected_char: char },
}

/// Stage 1: filename validation only. No hashing happens here or before this
/// -- the caller must not compute quick_hash unless this returns `Valid`.
pub fn validate(file: &ScannedFile) -> ValidationOutcome {
    match filename_validation::is_machine_dependent_filename(&file.file_name) {
        Some(detected_char) => ValidationOutcome::Invalid { detected_char },
        None => ValidationOutcome::Valid,
    }
}

pub struct NewVideo {
    pub id: String,
    pub file_path: String,
    pub file_name: String,
    pub file_size: u64,
    pub quick_hash: String,
    pub status: &'static str,
    pub mtime: i64,
}

/// Stage 2: only call after `validate` returned `Valid` and the caller has
/// computed `quick_hash`. `id` is generated by the caller (UUID v4) so this
/// function stays pure/deterministic.
///
/// `mtime` is carried through from `file.mtime` (not left `NULL`) so a
/// freshly registered row is immediately eligible for the cheap
/// unchanged/needs-rehash filter on its very next scan/poll -- omitting it
/// here would make every newly registered video look identical to a
/// pre-Phase-2 row (`mtime = NULL`), which `reconcile::classify_discovered_file`
/// deliberately always treats as "needs rehash", defeating the optimization
/// for anything registered after this point.
pub fn build_new_video(file: &ScannedFile, quick_hash: u64, id: String) -> NewVideo {
    NewVideo {
        id,
        file_path: file.file_path.clone(),
        file_name: file.file_name.clone(),
        file_size: file.file_size,
        quick_hash: quick_hash.to_string(),
        status: "online",
        mtime: file.mtime,
    }
}

pub struct NewSkippedFile {
    pub file_path: String,
    pub file_name: String,
    pub reason: &'static str,
    pub detected_char: char,
}

pub fn build_skipped_file(file: &ScannedFile, detected_char: char) -> NewSkippedFile {
    NewSkippedFile {
        file_path: file.file_path.clone(),
        file_name: file.file_name.clone(),
        reason: "machine_dependent_char",
        detected_char,
    }
}

const VIDEO_EXTENSIONS: &[&str] = &[
    "mp4", "mkv", "avi", "mov", "wmv", "flv", "webm", "m4v", "mpg", "mpeg", "ts", "m2ts", "3gp",
];

/// Whether `file_name`'s extension identifies it as a video file.
/// Case-insensitive.
pub fn is_video_file(file_name: &str) -> bool {
    match file_name.rsplit_once('.') {
        Some((_, ext)) => VIDEO_EXTENSIONS
            .iter()
            .any(|&video_ext| ext.eq_ignore_ascii_case(video_ext)),
        None => false,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn scanned(file_name: &str) -> ScannedFile {
        ScannedFile {
            file_path: format!("C:/videos/{file_name}"),
            file_name: file_name.to_string(),
            file_size: 1000,
            mtime: 1_700_000_000,
        }
    }

    #[test]
    fn validate_passes_normal_filenames() {
        assert!(matches!(
            validate(&scanned("movie.mp4")),
            ValidationOutcome::Valid
        ));
    }

    #[test]
    fn validate_rejects_machine_dependent_filenames() {
        match validate(&scanned("①movie.mp4")) {
            ValidationOutcome::Invalid { detected_char } => assert_eq!(detected_char, '①'),
            ValidationOutcome::Valid => panic!("expected Invalid"),
        }
    }

    #[test]
    fn build_new_video_fills_expected_fields() {
        let file = scanned("movie.mp4");
        let video = build_new_video(&file, 12345, "some-uuid".to_string());
        assert_eq!(video.id, "some-uuid");
        assert_eq!(video.file_path, "C:/videos/movie.mp4");
        assert_eq!(video.file_name, "movie.mp4");
        assert_eq!(video.file_size, 1000);
        assert_eq!(video.quick_hash, "12345");
        assert_eq!(video.status, "online");
        assert_eq!(video.mtime, 1_700_000_000);
    }

    #[test]
    fn build_skipped_file_fills_expected_fields() {
        let file = scanned("①movie.mp4");
        let skipped = build_skipped_file(&file, '①');
        assert_eq!(skipped.file_path, "C:/videos/①movie.mp4");
        assert_eq!(skipped.reason, "machine_dependent_char");
        assert_eq!(skipped.detected_char, '①');
    }

    #[test]
    fn is_video_file_accepts_known_extensions() {
        for name in ["movie.mp4", "movie.MKV", "movie.AvI", "clip.webm"] {
            assert!(is_video_file(name), "{name} should be a video file");
        }
    }

    #[test]
    fn is_video_file_rejects_non_video_extensions() {
        for name in ["document.txt", "archive.zip", "image.png", "audio.mp3"] {
            assert!(!is_video_file(name), "{name} should not be a video file");
        }
    }

    #[test]
    fn is_video_file_rejects_names_without_extension() {
        assert!(!is_video_file("no_extension"));
    }
}
